spring:
  application:
    name: Blog
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  jwt:
    secret: ${JWT_SECRET}
    accessTtlMinutes: ${JWT_ACCESS_TTL_MINUTES:15}
    refreshTtlDays: ${JWT_REFRESH_TTL_DAYS:14}